export const MAX_DESCRIPTION_LENGTH = 1000
export const MIN_PASSWORD_LENGTH = 5

export const REFRESH_TOKEN_SECRET_KEY = 'REFRESH_TOKEN_SECRET_KEY'
export const ACCESS_TOKEN_SECRET_KEY = 'ACCESS_TOKEN_SECRET_KEY'

export const ACCESS_TOKEN_EXPIRES_IN = '45m'
export const REFRESH_TOKEN_EXPIRES_IN = '7d'